/* eslint-disable */
// Generated by Wrangler
declare namespace Cloudflare {
  interface Env {
    OAUTH_KV: KVNamespace
    ENVIRONMENT: 'development' | 'staging' | 'production'
    MCP_SERVER_NAME: string
    MCP_SERVER_VERSION: string
    CLOUDFLARE_CLIENT_ID: string
    CLOUDFLARE_CLIENT_SECRET: string
    DEV_CLOUDFLARE_API_TOKEN: string
    MCP_OBJECT: DurableObjectNamespace<import('./src/dns-management.app').DNSManagementMCP>
    USER_DETAILS: DurableObjectNamespace<import('@repo/mcp-common/src/durable-objects/user_details.do').UserDetails>
    MCP_METRICS: AnalyticsEngineDataset
  }
}
interface Env extends Cloudflare.Env {}
